// Source-text guards on the interpret Edge Function.
//
// The model id used to be written twice — once at the API call, once at the `model_used`
// column — as two independent string literals, plus a third in the client wait screen. Two
// of those live in this file and can drift apart silently: a reading generated by one model
// would be recorded in Postgres as having come from another, with nothing failing.
import * as fs from 'fs';
import * as path from 'path';

function readFile(relPath: string): string {
  return fs.readFileSync(path.resolve(__dirname, '../../..', relPath), 'utf8');
}

const source = readFile('supabase/functions/interpret/index.ts');

/**
 * Comments stripped. Negative assertions ("this must not appear") have to run against code
 * only — otherwise a comment explaining *why* a thing is absent trips the very check that
 * enforces its absence.
 */
const code = source
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/(^|[^:])\/\/.*$/gm, '$1');

describe('interpret Edge Function model pinning', () => {
  it('declares the model id exactly once, as a constant', () => {
    expect(source).toContain("const INTERPRETATION_MODEL = 'claude-haiku-4-5';");
    expect(source.match(/'claude-haiku-4-5'/g)).toHaveLength(1);
  });

  it('uses that constant for both the API call and the recorded model_used', () => {
    expect(source).toContain('model: INTERPRETATION_MODEL,');
    expect(source).toContain('model_used: INTERPRETATION_MODEL,');
  });

  // The client mirrors the id for the wait screen's footer label only; it is cosmetic, but a
  // stale label tells the user the wrong thing about what read their dream.
  it('is mirrored by the client wait-screen label', () => {
    const screen = readFile('src/app/(main)/journal/[dreamId]/interpretation.tsx');
    expect(screen).toContain("const INTERPRETATION_MODEL = 'claude-haiku-4-5';");
  });

  // Haiku 4.5 predates the adaptive-thinking family: `output_config.effort` errors on it, and
  // `thinking` would spend the latency win the model was chosen for.
  it('sets neither thinking nor effort, which Haiku 4.5 does not accept', () => {
    expect(code).not.toContain('thinking:');
    expect(code).not.toContain('output_config');
  });
});

describe('interpret Edge Function tool contract', () => {
  it('forces the single tool by name rather than accepting any tool', () => {
    expect(source).toContain("tool_choice: { type: 'tool', name: 'format_interpretation' }");
  });

  it('constrains the tool input with strict mode', () => {
    expect(source).toContain('strict: true');
    expect(source).toContain('additionalProperties: false');
  });

  // Strict mode rejects the numeric/string range keywords outright — a schema carrying them
  // is a 400 on every request, not a degraded result. `enum` is the supported way to bound a
  // value, and it is what keeps symbolic_density inside its DB CHECK.
  it('uses only strict-compatible schema keywords', () => {
    expect(code).not.toMatch(/\b(minimum|maximum|minLength|maxLength|minItems|maxItems|pattern):/);
    expect(source).toContain('enum: [1, 2, 3, 4]');
  });

  // The image prompt is written here, in the same call that reads the dream, rather than
  // assembled from a template inside generate-image — which is the whole reason the Flux
  // prompts are specific to the dream at all.
  it('requires an image_prompt in the tool output and persists it', () => {
    expect(source).toContain("'image_prompt',");
    expect(source).toContain('image_prompt: input.image_prompt,');
    expect(source).toContain('imagePrompt: interpretation.image_prompt,');
  });

  it('leaves headroom for the nine-field tool payload', () => {
    const maxTokens = /max_tokens:\s*(\d+)/.exec(source);
    expect(maxTokens).not.toBeNull();
    expect(Number(maxTokens![1])).toBeGreaterThanOrEqual(2048);
  });
});

describe('interpret Edge Function metadata block', () => {
  // The archetype/themes reading is explicitly prompted to lean on the dreamer's own
  // log-time answers, so a field that silently stops being sent degrades the reading with
  // nothing failing.
  it.each([
    ['tone', 'Tone the dreamer assigned'],
    ['emotions', 'Emotions the dreamer tagged'],
    ['lucidity', 'Lucidity:'],
    ['clarity', 'Dream clarity/vividness'],
    ['ending', 'How the dream ended'],
    ['characters', 'Characters present'],
    ['places', 'Places/settings'],
    ['sleep quality', 'Sleep quality that night'],
    ['occurrence date', 'When the dream occurred'],
  ])('renders the %s line', (_label, needle) => {
    expect(source).toContain(needle);
  });

  // 015_dream_metadata.sql keeps these two on-device only. They must never reach a provider.
  it('never sends the on-device-only private context fields', () => {
    expect(code).not.toContain('day_stress');
    expect(code).not.toContain('dayStress');
    expect(code).not.toContain('presleep');
  });

  // Hemisphere is unknown, so a season would be a coin flip stated as fact.
  it('derives day-of-week and month from the date, never a season', () => {
    expect(source).toContain('formatOccurredAt');
    expect(code).not.toMatch(/\b(winter|summer|autumn|spring)\b/i);
  });
});

describe('interpret Edge Function style resolution', () => {
  // The client no longer sends a style, so this fallback is what makes the dreamer's own
  // profiles.interpretation_style setting take effect at all.
  it('falls back to the dreamer profile style when the request omits one', () => {
    expect(source).toContain("body.style ?? profile.interpretation_style ?? 'symbolic'");
  });
});
